name:                beam-mysql-haskell
version:             0.10.4.0
github:              "himura/beam-mysql-haskell"
license:             MIT
license-file:        LICENSE
author:              "Takahiro Himura"
maintainer:          "taka@himura.jp"
copyright:           "2023 Takahiro Himura"
synopsis:            Beam driver for mysql-haskell
description:         Beam driver for the MySQL database with the pure haskell driver <https://hackage.haskell.org/package/mysql-haskell mysql-haskell>.
                     Please see the README on GitHub at <https://github.com/himura/beam-mysql-haskell#readme>
category:            Database

tested-with: GHC ==9.8.4 || ==9.6.6

extra-source-files:
- README.md
- CHANGELOG.md

flags:
  build-examples:
    default: False
    manual: True
  use-test-container:
    default: False
    manual: True

dependencies:
- base >= 4.10 && < 5
- beam-core >= 0.10
- bytestring >=0.10.2.0 && <0.13
- dlist >= 0.7.1.2 && <1.1
- free >= 4.12 && <5.3
- io-streams >=1.2 && <2.0
- mtl >= 2.2.1 && <2.4
- mysql-haskell >= 1.0
- scientific >=0.3 && <0.4
- text >=1.1 && <2.2
- time >=1.5.0 && <1.13
- unliftio >= 0.1.0.0 && < 0.3
- unliftio-core >= 0.1.0.0 && <0.3

language: GHC2021

default-extensions:
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DerivingStrategies
- DerivingVia
- DuplicateRecordFields
- FunctionalDependencies
- GADTs
- LambdaCase
- MultiWayIf
- OverloadedLabels
- OverloadedRecordDot
- OverloadedStrings
- PackageImports
- QuasiQuotes
- RecordWildCards
- StrictData
- TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  ghc-options:
  - -Werror
  - -Wmissing-export-lists

tests:
  beam-mysql-haskell-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - beam-mysql-haskell
    - resource-pool
    - tasty
    - tasty-th
    - tasty-hunit
    when:
    - condition: flag(use-test-container)
      cpp-options:
      - -DUSE_TEST_CONTAINER
      dependencies:
      - testcontainers

executables:
  examples:
    main:                Main.hs
    source-dirs:         examples
    when:
      - condition: flag(build-examples)
        then:
          ghc-options:
          - -threaded
          - -rtsopts
          - -with-rtsopts=-N
          dependencies:
          - beam-mysql-haskell
          - resource-pool
        else:
          buildable: False
