name:                beam-mysql-haskell
version:             0.10.0.0
github:              "himura/beam-mysql-haskell"
license:             MIT
license-file:        LICENSE
author:              "Takahiro Himura"
maintainer:          "taka@himura.jp"
copyright:           "2023 Takahiro Himura"
synopsis:            Beam driver for mysql-haskell
description:         Beam driver for the MySQL database with the pure haskell driver <https://hackage.haskell.org/package/mysql-haskell mysql-haskell>.
                     Please see the README on GitHub at <https://github.com/himura/beam-mysql-haskell#readme>
category:            Database

extra-source-files:
- README.md
- CHANGELOG.md

flags:
  build-examples:
    default: False
    manual: True

dependencies:
- base >= 4.10 && < 5
- beam-core >= 0.10
- binary >=0.8.3 && <0.9
- blaze-textual >=0.2 && <0.3
- bytestring >=0.10.2.0 && <0.13
- bytestring-lexing >=0.5 && <0.6
- data-default-class >=0.1.2 && <0.2
- deepseq >=1.4.6 && <1.6
- dlist
- free
- io-streams >=1.2 && <2.0
- memory >=0.14.4 && <0.19
- monad-loops >=0.4 && <0.5
- mtl
- mysql-haskell >= 1.0
- network >=2.3 && <4.0
- pem >=0.2.4 && <0.3
- scientific >=0.3 && <0.4
- text >=1.1 && <2.2
- time >=1.5.0 && <1.13
- unliftio
- unliftio-core
- vector >=0.8 && <0.14
- word-compat >=0.0 && <0.1

language: GHC2021

default-extensions:
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DerivingStrategies
- DerivingVia
- DuplicateRecordFields
- FunctionalDependencies
- GADTs
- LambdaCase
- MultiWayIf
- OverloadedLabels
- OverloadedRecordDot
- OverloadedStrings
- PackageImports
- QuasiQuotes
- RecordWildCards
- StrictData
- TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  ghc-options:
  - -Werror
  - -Wmissing-export-lists

tests:
  beam-mysql-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - beam-mysql-haskell
    - tasty
    - tasty-th
    - tasty-hunit

executables:
  examples:
    main:                Main.hs
    source-dirs:         examples
    when:
      - condition: flag(build-examples)
        then:
          ghc-options:
          - -threaded
          - -rtsopts
          - -with-rtsopts=-N
          dependencies:
          - beam-mysql-haskell
          - resource-pool
        else:
          buildable: False
