module Database.Beam.MySQL.Test.Integration.MySQLSpecific (mysqlSpecificTests) where

import Control.Exception (SomeException, try)
import Data.List (isInfixOf)
import Data.Text.Encoding qualified as T
import Database.Beam
import Database.Beam.MySQL
import Database.Beam.MySQL.Extra
import Database.Beam.MySQL.Full
import Database.Beam.MySQL.MySQLSpecific
import Database.Beam.MySQL.Test.Integration.Fixture
import Database.Beam.MySQL.Test.Integration.Setup
import Database.Beam.MySQL.Test.Schema
import Database.MySQL.Base qualified as MySQL
import Test.Tasty
import Test.Tasty.HUnit

mysqlSpecificTests :: IO MySQL.ConnectInfo -> IO MySQL.MySQLConn -> TestTree
mysqlSpecificTests ioConnInfo ioConn =
    testGroup
        "MySQL extensions"
        [ testCase "lastInsertId_ returns the id generated by the last insert" $ withCleanTables ioConn $ \conn -> do
            mLast <- runDB conn $ do
                runInsert $
                    insert blogDb.tableUser $
                        insertExpressions [User default_ (val_ "Alice")]
                runSelectReturningOne $ select $ pure lastInsertId_
            [user] <- runDB conn $ runSelectReturningList $ select $ all_ blogDb.tableUser
            mLast @?= Just (fromIntegral user.id)
        , testCase "schema_ returns the connected database name" $ do
            connInfo <- ioConnInfo
            conn <- ioConn
            mSchema <- runDB conn $ runSelectReturningOne $ select $ pure schema_
            mSchema @?= Just (T.decodeUtf8 (MySQL.ciDatabase connInfo))
        , testCase "rlike_ matches by regular expression" $ withCleanTables ioConn $ \conn -> do
            runDB conn $
                runInsert $
                    insert blogDb.tableUser $
                        insertValues
                            [ User 1 "Alice"
                            , User 2 "alex"
                            , User 3 "Bob"
                            ]
            users <- runDB conn $
                runSelectReturningList $
                    select $
                        orderBy_ (\u -> asc_ u.id) $ do
                            user <- all_ blogDb.tableUser
                            guard_ $ user.name `rlike_` val_ "^[Aa]l"
                            return user
            map (.name) users @?= ["Alice", "alex"]
        , testCase "lockingForUpdate_ runs without error" $ withCleanTables ioConn $ \conn -> do
            runDB conn insertSampleData
            users <-
                runDB conn $
                    runSelectReturningList $
                        select $
                            lockingForUpdate_ $
                                orderBy_ (\u -> asc_ u.id) $
                                    all_ blogDb.tableUser
            length users @?= 3
        , testCase "lockingForShare_ runs without error" $ withCleanTables ioConn $ \conn -> do
            runDB conn insertSampleData
            users <-
                runDB conn $
                    runSelectReturningList $
                        select $
                            lockingForShare_ $
                                orderBy_ (\u -> asc_ u.id) $
                                    all_ blogDb.tableUser
            length users @?= 3
        , testCase "runInsertReturningOne returns the inserted row" $ withCleanTables ioConn $ \conn -> do
            mUser <-
                runDB conn $
                    runInsertReturningOne $
                        insert blogDb.tableUser $
                            insertExpressions [User default_ (val_ "Alice")]
            fmap (.name) mUser @?= Just "Alice"
            assertBool "id must be positive" $ maybe False (\u -> u.id > 0) mUser
        , testCase "runInsertReturningOne throws when table has no auto_increment" $ withCleanTables ioConn $ \conn -> do
            -- post_tag has a composite primary key without auto_increment.
            runDB conn $ do
                runInsert $ insert blogDb.tablePost $ insertValues samplePosts
                runInsert $ insert blogDb.tableTag $ insertValues sampleTags
            let action :: IO (Maybe PostTag)
                action =
                    runDB conn $
                        runInsertReturningOne $
                            insert blogDb.tablePostTag $
                                insertValues [PostTag (PostId 1) (TagId 2)]
            res <- try action :: IO (Either SomeException (Maybe PostTag))
            case res of
                Left e ->
                    assertBool ("unexpected exception: " <> show e) $
                        "BeamMySQLFailedToObtainAutoIncrementColumn" `isInfixOf` show e
                Right _ ->
                    assertFailure "expected BeamMySQLFailedToObtainAutoIncrementColumn"
        ]
